server:
  port: 9011

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.199.79.138:3306/security_authority?characterEncoding=UTF-8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true #允许我们自己覆盖spring放入到IOC容器的对象

mybatis:
  type-aliases-package: com.jay.springsecurity.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: debug
